### ISSUE TITLE
Translation of Value Set Display Fields

### ISSUE THREAD

**Issue by gabywh** [ehn-dcc-development/eu-dcc-valuesets#13]
Links to: https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/112

Initially opened on ehn-dcc-schema but is an ehn-dcc-valuesets issue only, so we continue here.

**Comment by ryanbnl** [comment]
Closing this as no changes are being made given the unclear future of the DCC. If the outlook changes it can be re-opened.
