### ISSUE TITLE
test-manf.json is not up to date

### ISSUE THREAD

**Issue by lari-kannisto** [ehn-dcc-development/eu-dcc-valuesets#14]
Link to: https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/121

Test name and manufacture ValueSet (test-manf.json) has not been updated after 1.7.2021. The admitted tests added in July are not in the current list. Please update!

**Comment by ryanbnl** [comment]
The definitive versions of tests are on the gateway, the version here is an old copy and will not be updated.
