### ISSUE TITLE
The Schema covers the root elements of the value sets but ignores the structure of the records 

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/eu-dcc-valuesets#22]
![image](https://user-images.githubusercontent.com/690575/137308390-ff3bc392-e10d-4a5f-9f89-69a76166845a.png)

* Green: Are covered
* Yellow: Are ignored (no rules for them) 

In the current situation any json structure (`object`) is accepted as value for the `valueSetValues` property. 

The structure of the actual values is well defined and the way it is consumed by all the application is already defined. An improved schema that will describe this in more details will prevent errors and ensure the quality.  

### References / Samples 
* Schema: https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/release/2.1.0/valueset.json
* Value set: https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/release/2.1.0/test-result.json

#### Improve Schema
* https://www.jsonschemavalidator.net/s/4OVqD3Bx

**Comment by dslmeinte** [comment]
(Going through the issues.)
Seems like a good idea. Put that into 2.4.0?

**Comment by dslmeinte** [comment]
Could we split that PR into two: 1. implement the validating Action, 2. improve the schema ?

**Comment by skounis** [comment]
> Could we split that PR into two: 1. implement the validating Action, 2. improve the schema ?

@dslmeinte the PR #23 is updated. It introduces changes related just to the schema. 

For the rest a new ticket and branch are prepared. A separate PR will follow 

- https://github.com/ehn-dcc-development/ehn-dcc-valuesets/issues/35

**Comment by skounis** [comment]
> > Hi @skounis, this is not my field of expertise (I am not an expert in json schema), so difficult to comment. Your approach seems to be logical, just please keep in mind that version string might be empty in some cases.
> > Hynek
> 
> Captured: https://github.com/ehn-dcc-development/ehn-dcc-valuesets/pull/23/files#r752373854

@kruzikh The schema required the existence of the property. The value could be just an empty string `""` .
