### ISSUE TITLE
Introduce the `validUntil` property in the `valueSetValues` object

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/eu-dcc-valuesets#26]
This change would be required for the EU DCC Gateway rather soon (first half of October), in order to handle the synchronization of RAT tests correctly, now that HSC is planning to apply grace periods.

### Task
Adjust the schema for describing the `validUntil` as an optional string property with date format for the `valueSetValues` object.

### How the synchronisation procedure works <b>now</b>?

<p class=MsoNormal><span lang=EN-IE>JRC maintains an online Common List of RATs
and exposes it in the JSON format. The list is frequently updated and is
available at the URI:<o:p></o:p></span></p>

- https://covid-19-diagnostics.jrc.ec.europa.eu/devices/hsc-common-recognition-rat

<p class=MsoNormal><span lang=EN-IE>A synchronization script is run by the EU
DCC Gateway every 24 hours, collecting information from the JSON and publishing
it in a different (simplified) format at the Gateway.<o:p></o:p></span></p>

<h3><span lang=EN-US>Values Mapping <o:p></o:p></span></h3>

<p class=MsoNormal><span lang=EN-IE>The following table describes the mapping
of the values between the JSON structures of the RAT value set as distributed
by the Gateway and the JRC API (JSON).<o:p></o:p></span></p>

Value set | Common List | Comments
-- | -- | --
valueSetId |   | covid-19-lab-test-manufacturer-and-name       The value is hardcoded
valueSetDate | .extracted_on[0:10] | Use the first 10 characters
  |   |  
valueSetValues |   |  
display | manufacturer.name + ", " + commercial_name |  
lang |   | en       the value is hardcoded
active | hsc_list_history.in_common_list | The most recent record
system |   | https://covid-19-diagnostics.jrc.ec.europa.eu/devices       The value is hardcoded
version | last_updated           hsc_list_history.list_date | If the latest entry in the history is “in_common_list” (true)       If the latest entry in the history is NOT “in_common_list” (false)

### How the synchronisation procedure should work <b>after the change</b>?

<p class=MsoNormal><span lang=EN-IE>JRC will change the handling of the JSON
file, not only listing changes performed to the status of a RAT test in the
past, but also including an upcoming change (which is in the future). The
information will become a new event in the hsc_list_history construct. <o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-IE>The flags (true/false) in the JRC database hsc_common_list
and hsc_mutual_recognition will continue conveying correct information about
the status of the RAT test at every single moment.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-IE>The updated synchronisation procedure with
described below with changes <u><span style='background:yellow;mso-highlight:
yellow'>highlighted</span></u>.<o:p></o:p></span></p>

Value set | Common List | Comments
-- | -- | --
valueSetId |   | covid-19-lab-test-manufacturer-and-name       The value is hardcoded
valueSetDate | .extracted_on[0:10] | Use the first 10 characters
  |   |  
valueSetValues |   |  
display | manufacturer.name + ", " + commercial_name |  
lang |   | en       the value is hardcoded
active | hsc_list_history.in_common_list | The most recent record that is not in the future.
valid_until   (new attribute) | hsc_list_history.list_date | Implementation remark: The addition of   this attribute is optional (useful mainly for issuance apps) and depends on   the possibility to implement in such a short time frame.       Null, if the most   recent record is in the past.   If the most recent   record is in the future, value from list_date.
system |   | https://covid-19-diagnostics.jrc.ec.europa.eu/devices       The value is hardcoded
version | last_updated           hsc_list_history.list_date | If the latest entry in the history is “in_common_list” (true)       If the latest entry in the history is NOT “in_common_list” (false)       Value from the   latest entry in the history that is not in the future.

**Comment by ryanbnl** [comment]
This was added to the schema as optional. At this point in the life-cycle we will not make a change to the valuesets themselves.
