### ISSUE TITLE
Align the release tags with the version of the Guidelines document 

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/eu-dcc-valuesets#34]
@dslmeinte suggested 

> I think I'd be useful to tag releases with the version number of the value set update (e.g. `vs-1.5` for the latest) as well. That way it's clearer that e.g. a 2.4.0 release only add this versioning process, but doesn't correspond to an update of the eHN value set. (Same goes for other purely technical/process-related changes to this repo.)
> https://github.com/ehn-dcc-development/ehn-dcc-valuesets/pull/33#issuecomment-971463706

**Comment by skounis** [comment]
@dslmeinte @kruzikh @ryanbnl I moved the discussion here so we could merge the PR and still keep track of the task. The comment in the PR may be lost after we finish with PR.

**Comment by skounis** [comment]
We currently have `1.x` tag not schematically related to the version of the Guidelines document. 

@dslmeinte My understanding is that you are suggestion a parallel tagging policy with a prefix.  

Since the history is not actually relevant nor there is any system depending on past releases I sense it is safe to 
1. Introduce a new model 
2. Keep the old model live for a certain amount of time and kill it when it will become completely irrelevant

I'm in favor of the `vX.X.X` pattern which was not use so far which is broadly used. Since it does not collide with the existing versions I would suggest to go with it and mark/tag the versions 
- `v1.5.0` - https://github.com/ehn-dcc-development/ehn-dcc-valuesets/releases/tag/2.3.0
- `v1.4.0` - https://github.com/ehn-dcc-development/ehn-dcc-valuesets/releases/tag/2.2.0
- `v1.3.0` - https://github.com/ehn-dcc-development/ehn-dcc-valuesets/releases/tag/2.1.0
- `v1.2.0` - https://github.com/ehn-dcc-development/ehn-dcc-valuesets/releases/tag/2.0.0

> It's not clear which releases correspond to the document `1.1` and `1.0`

**Comment by dslmeinte** [comment]
@skounis Indeed: parallel tagging. I do this for [CertLogic](https://github.com/ehn-dcc-development/dgc-business-rules/tags) as well: there are tags for versions of the specification, tags for versions of the JavaScript implementation, and likewise for Kotlin, and Dart.

**Comment by skounis** [comment]
In this case I sense that the `vX.X.X` pattern, e.g. `v1.5.0` will be a bit misleading. It could be perceived as the `semver` of the code, something that is not correct. For example the version `1.6.0` of the guidelines may introduces changes in the schema that will force us to go up to `3.x` due to API changes. 

What the `vs-` prefix stands for?

**Comment by kruzikh** [comment]
Use rather sgs or SGS for Subgroup on Semantics - this is widely being used and understood by many.

**Comment by skounis** [comment]
@dslmeinte @kruzikh @ryanbnl Should we go with the prefix `sgs-` so we have `sgs-1.5.0`, `sgs-1.4.0` etc.?

**Comment by kruzikh** [comment]
@skounis What about dcc-vs-1.5.0? Specifying rather DCC Value Set guidelines version rather than its source.

**Comment by skounis** [comment]
the repository is already about the DCC Valuesets. The scope of this parallel tagging is to link the releases with the version of the Guidelines Document. So I would be in favor of something the reflects this.

**Comment by dslmeinte** [comment]
I added tags for versions 1.2 through to 1.5 of (updates to) the value set document.

**Comment by ryanbnl** [comment]
Closed as I believe that this was either completed or abandoned.

**Comment by dslmeinte** [comment]
We've adopted this, and are tagging releases with the version of the guidelines document.
