### ISSUE TITLE
Prepare Actions for validation

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/eu-dcc-valuesets#35]

**Comment by dslmeinte** [comment]
@skounis Is this issue still relevant? (I can't tell because there's no description.)

**Comment by skounis** [comment]
This is related to the suggestion in #22 and is about GitHub actions that will validate the JSON files

**Comment by dslmeinte** [comment]
What does this issue address that #22 doesn't: do you mean setting up a GitHub Action? If #22 is already the whole story, it'd say we close this one. If it isn't, let's clarify it, so we can implement it.

**Comment by skounis** [comment]
This issue makes sense only if we improve the schema and tighten the validation. 

I suggest to close it for the moment. If there is any progress on #22 we could open it again
