### ISSUE TITLE
Spelling issue in test manufacturer 1343

### ISSUE THREAD

**Issue by SMonday** [ehn-dcc-development/eu-dcc-valuesets#43]
Manufacturer with ID 1343 has a typo:

Is: **Zhezhiang** Orient Gene Biotech Co., Ltd
Should be: **Zhejiang** Orient Gene Biotech Co.,Ltd.

See also [https://covid-19-diagnostics.jrc.ec.europa.eu/devices/detail/1343](https://covid-19-diagnostics.jrc.ec.europa.eu/devices/detail/1343)

**Comment by skounis** [comment]
This refers to 

* https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/fdff116a58df3066116604865f96982fcf04947e/test-manf.json#L615

However, the RATs are not maintained in this repository anymore. The Gateway is pulling them directly from the database of JRC.

 To avoid any confusion I would suggest taking the `test-manf.json` file completely out. 

@ryanbnl @dslmeinte ?

**Comment by dslmeinte** [comment]
@skounis Agreed, but we should also provide clear instructions on how, and preferably a script to obtain the `test-manf.json` from the Gateway.

**Comment by ryanbnl** [comment]
Add to the agenda for Friday. The options are:

* Leave as-is.
* Rename **test-manf-snapshot-yyyy-dd-mm.json** so it's clear that this file is a snapshot!
* Remove completely.
* Remove but provide an example containing a small number of fictional examples, using a different but similar file name to avoid confusion.
* Use github actions to automatically update the file daily.

**Comment by dslmeinte** [comment]
I vote for option #4: replace `test-manf.json` with an example file with a different name.

**Comment by ryanbnl** [comment]
Resolved
