### ISSUE TITLE
source-update/update-rat.sh does not work

### ISSUE THREAD

**Issue by mirehak** [ehn-dcc-development/eu-dcc-valuesets#55]
Greetings,
because of format change at https://covid-19-diagnostics.jrc.ec.europa.eu/devices/hsc-common-recognition-rat this script no longer works. I have no clue if that format change is permanent but:
- we lost the `.extracted_on` property
- and all manufacturers/devices are directly listed under root (`.device_list[]` -> `.[]`)

**Comment by danka74** [comment]
There might be more issues. I get "version": null and "active": null. Will investigate.

**Comment by skounis** [comment]
Related PRs
* https://github.com/ehn-dcc-development/eu-dcc-valuesets/pull/56
* https://github.com/ehn-dcc-development/eu-dcc-valuesets/pull/57

**Comment by ryanbnl** [comment]
Closing as it was previously decided not to update the script.
