### ISSUE TITLE
Introduce the description fields

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/eu-dcc-valuesets#6]
For all the valuesets we may introduce a descritpion field for keeping a more friendly name, a descritpion or even the purpose of it. 

eg:
```
{
  "valueSetId": "sct-vaccines-covid-19",
  "valueSetDescription": "The list with all the accepted by the EC vaccines." 
  ...
```

**Comment by ryanbnl** [comment]
Closing this as no changes are being made given the unclear future of the DCC. If the outlook changes it can be re-opened.
